# This script is generated by ChatGPT
# OpenAI. (2023). ChatGPT (Feb 13 version) [Large language model]. https://chat.openai.com

#!/usr/bin/env bash
set -euo pipefail

# Run this from the project root after `make`
# It generates 3 larger CSV partitions, starts the server, then starts 3 workers.

PORT=58800
SERVER_IP="127.0.0.1"
N_WORKERS=3
SAMPLES_PER_WORKER=5000
OUT_DIR="test_data_large"

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/data_*.csv "$OUT_DIR"/server.log "$OUT_DIR"/worker_*.log

python3 - <<'PY'
import csv
import os
import random
from pathlib import Path

out_dir = Path("test_data_large")
out_dir.mkdir(exist_ok=True)

random.seed(209)

n_workers = 3
samples_per_worker = 5000

for worker_id in range(1, n_workers + 1):
    path = out_dir / f"data_{worker_id}.csv"
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        for _ in range(samples_per_worker):
            x1 = random.random()
            x2 = random.random()
            # Bias term in column 0, matching your model/training code.
            label = 1.0 if (x1 + x2 > 1.0) else 0.0
            writer.writerow([1.0, x1, x2, label])
print(f"Created {n_workers} files in {out_dir} with {samples_per_worker} samples each.")
PY

if [ ! -x ./server ] || [ ! -x ./worker ]; then
    echo "Please run: make"
    exit 1
fi

cleanup() {
    jobs -pr | xargs -r kill 2>/dev/null || true
}
trap cleanup EXIT

echo "Starting server..."
./server > "$OUT_DIR/server.log" 2>&1 &
SERVER_PID=$!

sleep 1

echo "Starting workers..."
./worker "$SERVER_IP" "$OUT_DIR/data_1.csv" > "$OUT_DIR/worker_1.log" 2>&1 &
W1=$!
./worker "$SERVER_IP" "$OUT_DIR/data_2.csv" > "$OUT_DIR/worker_2.log" 2>&1 &
W2=$!
./worker "$SERVER_IP" "$OUT_DIR/data_3.csv" > "$OUT_DIR/worker_3.log" 2>&1 &
W3=$!

wait "$W1" "$W2" "$W3"
wait "$SERVER_PID"

echo
echo "=== Server log (last 20 lines) ==="
tail -n 20 "$OUT_DIR/server.log" || true

echo
echo "=== Worker 1 log (last 10 lines) ==="
tail -n 10 "$OUT_DIR/worker_1.log" || true

echo
echo "=== Worker 2 log (last 10 lines) ==="
tail -n 10 "$OUT_DIR/worker_2.log" || true

echo
echo "=== Worker 3 log (last 10 lines) ==="
tail -n 10 "$OUT_DIR/worker_3.log" || true