# This script is generated by ChatGPT
# OpenAI. (2023). ChatGPT (Feb 13 version) [Large language model]. https://chat.openai.com

#!/usr/bin/env bash
set -euo pipefail

# Run this from the project root after `make`
# It generates CSV partitions, starts the server, then starts that many workers.


SERVER_IP="127.0.0.1"
N_WORKERS="${1:-3}"
SAMPLES_PER_WORKER=5000
OUT_DIR="test_data_large"

if ! [[ "$N_WORKERS" =~ ^[1-9][0-9]*$ ]]; then
    echo "Usage: $0 [num_workers]"
    exit 1
fi

mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/data_*.csv "$OUT_DIR"/server.log "$OUT_DIR"/worker_*.log

N_WORKERS="$N_WORKERS" SAMPLES_PER_WORKER="$SAMPLES_PER_WORKER" OUT_DIR="$OUT_DIR" python3 - <<'PY'
import csv
import os
import random
from pathlib import Path

out_dir = Path(os.environ["OUT_DIR"])
out_dir.mkdir(exist_ok=True)

random.seed(209)

n_workers = int(os.environ["N_WORKERS"])
samples_per_worker = int(os.environ["SAMPLES_PER_WORKER"])

for worker_id in range(1, n_workers + 1):
    path = out_dir / f"data_{worker_id}.csv"
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        for _ in range(samples_per_worker):
            x1 = random.random()
            x2 = random.random()
            # Bias term in column 0, matching your model/training code.
            label = 1.0 if (x1 + x2 > 1.0) else 0.0
            writer.writerow([1.0, x1, x2, label])
print(f"Created {n_workers} files in {out_dir} with {samples_per_worker} samples each.")
PY

if [ ! -x ./server ] || [ ! -x ./worker ]; then
    echo "Please run: make"
    exit 1
fi

cleanup() {
    jobs -pr | xargs -r kill 2>/dev/null || true
}
trap cleanup EXIT

echo "Starting server for $N_WORKERS workers..."
./server "$N_WORKERS" > "$OUT_DIR/server.log" 2>&1 &
SERVER_PID=$!

sleep 1

echo "Starting workers..."
worker_pids=()
for worker_id in $(seq 1 "$N_WORKERS"); do
    ./worker "$SERVER_IP" "$OUT_DIR/data_${worker_id}.csv" > "$OUT_DIR/worker_${worker_id}.log" 2>&1 &
    worker_pids+=("$!")
done

for pid in "${worker_pids[@]}"; do
    wait "$pid"
done
wait "$SERVER_PID"

echo
echo "=== Server log (last 20 lines) ==="
tail -n 20 "$OUT_DIR/server.log" || true

for worker_id in $(seq 1 "$N_WORKERS"); do
    echo
    echo "=== Worker ${worker_id} log (last 10 lines) ==="
    tail -n 10 "$OUT_DIR/worker_${worker_id}.log" || true
done
